spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:1010/
          predicates:
            - Path=/customers/**
        - id: r2
          uri: http://localhost:1011/
          predicates:
            - Path=/products/**